asset_name: "Factoring (FIC)"
categoria: "Renta Fija"
subcategoria: "Facturas/Fondos de Inversión"
nivel_riesgo: "Medio"
fuente: "datos.gov.co — Fondos de Inversión Colectiva"
codigo_negocio: 93229
tipo_participacion: 800
years: 1
